# Generated by Django 6.0.5 on 2026-05-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_schoolknowledgechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolknowledgechunk',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
