# Generated by Django 6.0.5 on 2026-07-02 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_company_logo_url_company_logo'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=150, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=150, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=300, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.plan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['razorpay_order_id'], name='billing_pay_razorpa_b1b083_idx'), models.Index(fields=['razorpay_payment_id'], name='billing_pay_razorpa_0baaec_idx'), models.Index(fields=['status'], name='billing_pay_status_b7739e_idx'), models.Index(fields=['company'], name='billing_pay_company_247e61_idx')],
            },
        ),
    ]
