# Generated by Django 6.0.5 on 2026-06-02 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bot_type', models.CharField(choices=[('school', 'School'), ('healthcare', 'Healthcare'), ('ecommerce', 'E-Commerce'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('welcome_message', models.TextField(default='Hello! How can I help you today?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='accounts.company')),
            ],
        ),
    ]
