# Generated by Django 6.0.5 on 2026-06-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='auto_recrawl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='last_crawled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('active', 'Active'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
