# Generated by Django 6.0.5 on 2026-06-05 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_websitechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitechunk',
            name='chatbot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='bots.chatbot'),
        ),
        migrations.AddField(
            model_name='websitechunk',
            name='source_type',
            field=models.CharField(default='website', max_length=50),
        ),
        migrations.AddField(
            model_name='websitechunk',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='websitechunk',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='bots.websitepage'),
        ),
    ]
