# Generated by Django 6.0.5 on 2026-06-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_botknowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='botknowledge',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botknowledge',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
