# Generated by Django 6.0.5 on 2026-06-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_botknowledge_deleted_at_botknowledge_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitechunk',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
