# Generated by Django 6.0.5 on 2026-06-05 09:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_websitechunk_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='installed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='is_installed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='theme_color',
            field=models.CharField(default='#0d6efd', max_length=20),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='widget_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='widget_position',
            field=models.CharField(default='bottom-right', max_length=30),
        ),
    ]
