# Generated by Django 6.0.5 on 2026-06-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0010_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
