# Generated by Django 6.0.5 on 2026-06-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_chatbot_deleted_at_chatbot_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
