# Generated by Django 6.0.5 on 2026-06-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0012_websitepage_deleted_at_websitepage_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitechunk',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitechunk',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
